### ISSUE TITLE
.htaccess/password access

### ISSUE THREAD

**Issue by dogboy23** [drgroot/docker-containers#12]
Not sure how you'd go about this, but probably worth implementing. My personal setup is via VPN only, so my interface is safe, but it might be better on less restricted networks

**Comment by drgroot** [comment]
are you referring to adding htpassword access to the rutorrent web interface?

**Comment by dogboy23** [comment]
yarp... is it possible to do from a volume or does it need to be done within the container?

**Comment by drgroot** [comment]
I'm trying to think of an elegant solution to it. We could have so if you drop a file called '.htaccess' in the /config volume mount, it will `ln -s` it to the web folder or something. 

What are your thoughts?

**Comment by drgroot** [comment]
Finished!
