### ISSUE TITLE
Read/write to dropbox folder on synology

### ISSUE THREAD

**Issue by dogboy23** [drgroot/docker-containers#25]
Autotools has some issue doing read/writes to a dropbox folder. I have no problem r/w from /bin/sh command line, as UID is root. However rtorrent is run as user abc. If I change the environment variables to my synology login PUID and PGID [1028 & 100], the container throws an error "unknown user abc" and hangs.

Not sure if the problem is in DSM or the container.

Nick

**Comment by drgroot** [comment]
which container? rtorrent or deluge?

**Comment by drgroot** [comment]
tested, no issue
